apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: mealie
  namespace: flux-system
spec:
  interval: 15m
  url: oci://ghcr.io/mealie-recipes/mealie
  ref:
    tag: nightly
