apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: media
  annotations:
    test: force update
spec:
  interval: 15m
  chart:
    spec:
      chart: immich
      version: 17.51.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${IMMICH_IP}
        ports:
          main:
            port: 2283 # Default immich port
        annotations:
          metallb.universe.tf/allow-shared-ip: "true"
    machinelearning:
      enabled: false
    persistence:
      thumbs:
        enabled: true
        type: nfs
        path: /mnt/playground/media/immich/thumbs
        mountPath: "/usr/src/app/upload/thumbs"
        server: 192.168.1.98
        targetSelector:
        # Main pod/container is server
          main:
            main: {}
          microservices:
            microservices: {}
      uploads:
        enabled: true
        type: nfs
        path: /mnt/playground/media/immich/uploads
        mountPath: /usr/src/app/upload/upload
        server: 192.168.1.98
        targetSelector:
          # Main pod/container is server
          main:
            main: {}
          microservices:
            microservices: {}
      library:
        enabled: true
        type: nfs
        path: /mnt/playground/media/immich/library
        mountPath: /usr/src/app/upload/library
        server: 192.168.1.98
        targetSelector:
          # Main pod/container is server
          main:
            main: {}
          microservices:
            microservices: {}
      backups:
        enabled: true
        type: nfs
        path: /mnt/playground/media/immich/backups
        mountPath: /usr/src/app/upload/backups
        server: 192.168.1.98
        targetSelector:
          # Main pod/container is server
          main:
            main: {}
          microservices:
            microservices: {}
      profile:
        enabled: true
        type: nfs
        path: /mnt/playground/media/immich/profile
        mountPath: /usr/src/app/upload/profile
        server: 192.168.1.98
        targetSelector:
          # Main pod/container is server
          main:
            main: {}
          microservices:
            microservices: {}
      video:
        enabled: true
        type: nfs
        path: /mnt/playground/media/immich/encoded-video
        mountPath: /usr/src/app/upload/encoded-video
        server: 192.168.1.98
        targetSelector:
          # Main pod/container is server
          main:
            main: {}
          microservices:
            microservices: {}