apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: immich
      version: 17.50.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${IMMICH_IP}
        ports:
          main:
            port: 2283 # Default immich port
        annotations:
          metallb.universe.tf/allow-shared-ip: "true"
    persistence:
      media:
        enabled: true
        type: nfs
        path: /mnt/playground/media
        mountPath: "/Media"
        server: 192.168.1.98
      thumbs:
        enabled: true
        type: nfs
        path: /mnt/playground/media/photos/thumbs
        mountPath: "/usr/src/app/upload/thumbs"
        server: 192.168.1.98
        targetSelector:
        # Main pod/container is server
          main:
            main: {}
          microservices:
            microservices: {}
      uploads:
        enabled: true
        type: nfs
        path: /mnt/playground/media/photos/uploads
        mountPath: /usr/src/app/upload/upload
        server: 192.168.1.98
        targetSelector:
          # Main pod/container is server
          main:
            main: {}
          microservices:
            microservices: {}
