apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:2EiJVmQi/vy8jxKO+2cLeeQ3lXMNtjQLdMNOE6ShEQHq4m9lcZ8EglBnnTL5NZS3cO2ITjVKdnQ6dXD5MrU0YV/XIEI7QTSFXHAdtQeP/eOvMIWqMxnXUx3/TRzozm9hlffISR3XNhEzxcHFH9hq6qoMDpJpXEGQKt+goN6Ux/s6xkSBwEOSgicj5Ve90dYv9pF7Tl0NKnnqezNWhUpq/GOTQFjw3mT7c6dhMXZnwG+SDyw4/cIfY4c3IINDXNVzOkGKfndFZx6ZUSzlONPlcxLpQ/zFRPtsA0NeiWgl8WgEcIedDtkO2HBE/d6ijJSIGU+Dli9V+xiBQcF5raNZitQNpoSo8t5MmU+J6s5z7cF2PKbhqfebqLDQi1NbLgxR,iv:GEFdEN2JflRDbzMfmrM5HR7R0ymsAHunaOk5h6fBnUg=,tag:US8v+qf2QpH79JGXaZcZYw==,type:str]
    identity.pub: ENC[AES256_GCM,data:CdTJAcHHS8Vm0PEsTdT3ErZmt6ugYSyu22KLnL2fzIOWD5abaz/oBn9tM04mAE1IoZIqL4tmY2kWWe0RDcj5D0maDz9IwAlD5u4wVGeixEy+Uy4YTOo/qdCNfSYRsYRUAasgl3C+Sg1Au3YjijNyhFId8VZtJwgG/mGe7c9kLf4LGRQ1V1exn4xuTyaAbeY2Fplh1BPvWqIDcNX2PUPo23Zogt3xNNAkIb0LrPukypasZibySz4LiMG0doO4220xUnMxd+NKiiIF00onsQ==,iv:ZaK09QbPuAKa4BcnUONdn3/PIJ2sD5rwD1ratuIgyac=,tag:9ijlIfWxjs7S0eEXv2wcug==,type:str]
    known_hosts: ENC[AES256_GCM,data:8ch3afSJgWEa8SuT3y7oZS9i51Yr3L3l9LHNU81UX6MItSSYjzKfhppEdu/zkLUW7fTJMFbaBiHkMLZ/huYwklK64ePvCZX8LXckoThReup0CyZ8y78rcNfZXFY69v6Wy8da9O0Gu8umoaELHXKJ+7Qk/oUr44qOnRqMWPrawJvEZCMpIowckGo4XoV1F3tWfewvPITqxm+TyHghUrBitqJ7jbn7x0GMR8AO,iv:eP9rCmR8LnTCBbo+v92iRynDbI2Xkph7/Q/PosRvMRg=,tag:bc0B2S+L8Y4BCGbUiDvaiw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14gcn729zzzgecu4fz967hnpc6q3t7qcrzkkgtscpcf9wjtx03pyqjmlm3j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYK0U2aTVWUnp3TnZKZG9a
            eHhMb3hKTmI3YzVSSjQ2SklyK0lnQm9ydjJnClRuVkQ4Q3o1SFcxdjVYdllKN1dn
            QXNXclEyNm9NeHVXZFZ4SFFyVnorSU0KLS0tIEtHK1hFNUg1UXZzNGtlTzlZWVN2
            c2lJZGl1VERWeFZRSXEwSlRQcHB4SDAKykN07sQpVQhWQ8mww/QDfbm6yvMkanJf
            u5VuP7Hio7v8Tm9ZL7C7O79UuzW1axTFK6IetBRJK+t+z8u9/uTCOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-06T19:54:45Z"
    mac: ENC[AES256_GCM,data:NJVRlxiseP7OqWS+MYTGnc7/t0vhHMnEYVJgStQJJ6PeSNtQQL6CRDrpCd37eFoZ643KwrPtPlG7PKfDPWOd4XyTd0F1/cQIxH4vt3Ad/nXEAu72y6ZZYL+ZlIH8BhZwvHII8UBkmYh0E6u7k82/c+7bj8MuTP5BLhoFHCvoGLg=,iv:P5i0EKLVneYgaV0KI/wrKVfFpd6UMqkQxvpyDSONAYM=,tag:g/9A4ZTofJpb7A7bIPhLpQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
