apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 15m
  chart:
    spec:
      chart: homepage
      version: 9.7.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    forceConfigFromValues: true
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${HOMEPAGE_IP}
        ports:
          main:
            port: 9000 # Default homepage port
    configmap:
      config:
        enabled: true
        data:
          custom.js: ""
          custom.css: ""
          kubernetes.yaml: |
            mode: cluster
          settings.yaml: |
            ---
            # For configuration options and examples, please see:
            # https://gethomepage.dev/latest/configs/settings

            providers:
              openweathermap: openweathermapapikey
              weatherapi: weatherapiapikey
          widgets.yaml: |
            ---
            # For configuration options and examples, please see:
            # https://gethomepage.dev/latest/configs/widgets

            - resources:
                cpu: true
                memory: true
                disk: /

            - search:
                provider: duckduckgo
                target: _blank
          services.yaml: |
            ---
            # For configuration options and examples, please see:
            # https://gethomepage.dev/latest/configs/services
            - Torrenting:
                - Lidarr:
                    href: http://192.168.1.98:8686/
                    description: Manager in charge of finding music to download
                    target: _self
                    icon: lidarr.png
                    widget:
                        type: lidarr
                        url: http://192.168.1.98:8686
                        key: 01d9617a49b1413698c686b71dec8598
                        enableQueue: true
                - Prowlarr:
                    href: http://192.168.1.98:30050/
                    description: Indexer Manager
                    target: _self
                    icon: prowlarr.png
                    widget:
                        type: prowlarr
                        url: http://192.168.1.98:30050
                        key: 4d207ffae2d74fca90b25a56f407bf74
                        enableQueue: true
                - qBittorrent:
                    href: http://192.168.1.98:10095/
                    description: Download Client
                    target: _self
                    icon: qbittorrent.png
                    widget:
                        type: qbittorrent
                        url: http://192.168.1.98:10095
                        username: admin
                        password: StevensP0int
                - Radarr:
                    href: http://192.168.1.98:30025/
                    description: Manager in charge of finding movies to download
                    target: _self
                    icon: radarr.png
                    widget:
                        type: radarr
                        url: http://192.168.1.98:30025
                        key: 07eac588fd8c40028725f2b43323f093
                        enableQueue: true
                - Sonarr:
                    href: http://192.168.1.98:30027/
                    description: Manager in charge of finding TV shows to download
                    target: _self
                    icon: sonarr.png
                    widget:
                        type: sonarr
                        url: http://192.168.1.98:30027
                        key: 17281943d614437581416d5217e31de4
                        enableQueue: true   
            - Media & Useful Tools:
                - Audiobookshelf:
                    href: http://192.168.1.98:10223/
                    description: Listen to audiobooks
                    target: _self
                    icon: audiobookshelf.png
                - Home Assistant:
                    href: http://192.168.1.132:8123/
                    description: Home Automation
                    target: _self
                    icon: home-assistant.png
                - Jellyfin:
                    href: http://192.168.1.98:30013/
                    description: Watch TV shows and movies
                    target: _self
                    icon: jellyfin.png
                    widget:
                        type: jellyfin
                        url: http://192.168.1.98:30013
                        key: 23d29d34c9254d868512de421d86a2b7
                        enableBlocks: true # optional, defaults to false
                        enableNowPlaying: true # optional, defaults to true
                - Kavita:
                    href: http://192.168.1.98:30069/
                    description: Read E-books and Graphic Novels
                    target: _self
                    icon: kavita.png
                - Mealie:
                    href: http://192.168.1.98:31001/
                    description: Find Local Recipes here
                    target: _self
                    icon: mealie.png
                - Navidrome:
                    href: http://192.168.1.98:4533/
                    description: Listen to music
                    target: _self
                    icon: mdi-album
                    widget:
                        type: navidrome
                        url: http://192.168.1.98:4533
                        user: admin
                        token: a60dd926aa10c84564cc54c5ba99643d
                        salt: pig
            - Misc.:
                - Calibre:
                    href: http://192.168.1.98:8084/
                    description: manage e-book metadata
                    icon: calibre.png
                    target: _self

                - TrueNAS:
                    href: http://192.168.1.98/
                    description: Truenas instance
                    icon: truenas-scale.png
                    target: _self
                    widget:
                        type: truenas
                        url: http://192.168.1.98/
                        key: 1-wV8XGbJTbYL1w0RkqiSEDsXyaiOSObz1MS1mgh7weaTd8XYWintG4ybtJt9V45nm
                - Uptime Kuma:
                    href: http://192.168.1.98:3001/
                    description: validate that services are running by checking endpoints
                    icon: uptime-kuma.png
                    target: _self
            - External:
                - Myanonamouse:
                    href: https://www.myanonamouse.net/
                    description: Private torrent server for E-books and Audiobooks
                    icon: mdi-rodent
                    target: _self
          bookmarks.yaml: |
            ---
            # For configuration options and examples, please see:
            # https://gethomepage.dev/latest/configs/bookmarks

            - Developer:
                - Github:
                    - abbr: GH
                      href: https://github.com/

            - Social:
                - Reddit:
                    - abbr: RE
                      href: https://reddit.com/

            - Entertainment:
                - YouTube:
                    - abbr: YT
                      href: https://youtube.com/

            - TrueCharts:
                - TrueCharts:
                    - abbr: TC
                      icon: https://truecharts.org/svg/favicon.svg
                      href: https://truecharts.org
                      description: "TrueCharts Website"
                - Github:
                    - abbr: GH
                      icon: https://github.com/fluidicon.png
                      href: https://github.com/truecharts
                      description: "TrueCharts GitHub"
                - Open Collective:
                    - abbr: TC
                      icon: https://opencollective.com/favicon.ico
                      href: https://opencollective.com/truecharts
                      description: "TrueCharts Open Collective"
                - Discord:
                    - abbr: DC
                      icon: https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://discord.com&size=32
                      href: https://truecharts.org/s/discord
                      description: "TrueCharts Discord"