apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: sonarr
spec:
  interval: 15m
  chart:
    spec:
      chart: sonarr
      version: 23.6.5
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${RADARR_IP}
        ports:
          main:
            port: 8989 # Default sonarr port
    persistence:
      media:
        enabled: true
        type: nfs
        path: ${NFS_SHARE}
        mountPath: /Media
        server: ${TRUENAS_IP}
