apiVersion: v1
kind: ConfigMap
metadata:
  name: qbittorrent-custom-config
  namespace: media
data:
  qBittorrent.conf: |
    [Application]
    FileLogger\Age = 1
    FileLogger\AgeType = 1
    FileLogger\Backup = true
    FileLogger\DeleteOld = true
    FileLogger\Enabled = true
    FileLogger\MaxSizeBytes = 66560
    FileLogger\Path = /config/qBittorrent/logs

    [BitTorrent]
    Session\AddTorrentPaused = true
    Session\DefaultSavePath = /media
    Session\DisableAutoTMMByDefault = false
    Session\ExcludedFileNames =
    Session\GlobalMaxRatio = 0
    Session\GlobalMaxSeedingMinutes = -1
    Session\MaxActiveTorrents = 200
    Session\MaxActiveUploads = 200
    Session\MaxRatioAction = 0
    Session\Port = 49999
    Session\QueueingSystemEnabled = true
    Session\TempPath = /media/temp
    Session\TempPathEnabled = true
    Session\TorrentContentLayout = Subfolder

    [Core]
    AutoDeleteAddedTorrentFile = Never

    [LegalNotice]
    Accepted = true

    [Meta]
    MigrationVersion = 6

    [Network]
    Cookies = @Invalid()
    Proxy\HostnameLookupEnabled = false
    Proxy\Profiles\BitTorrent = true
    Proxy\Profiles\Misc = true
    Proxy\Profiles\RSS = true

    [Preferences]
    Connection\PortRangeMin = 49999
    General\Locale = en
    MailNotification\req_auth = true
    WebUI\Address = *
    WebUI\AuthSubnetWhitelist = 192.168.1.0/24
    WebUI\AuthSubnetWhitelistEnabled = true
    WebUI\CSRFProtection = false
    WebUI\ClickjackingProtection = false
    WebUI\HostHeaderValidation = false
    WebUI\LocalHostAuth = false
    WebUI\Password_PBKDF2 = "@ByteArray(xpep8K7Lm6NGX7ljuE3N+g==:I6vp5A9ZJIbiOl+J1Hcqc8v5acOBuEIDvM4XMaRjHwqJaNG9XFhq8XEJ8Ia4x91J575jaX6JSOZt/TmFPGO+yQ==)"
    WebUI\Port = 10095
    WebUI\UseUPnP = false

    [RSS]
    AutoDownloader\DownloadRepacks = true
    AutoDownloader\SmartEpisodeFilter = s(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"
