apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  # suspend: true 
  interval: 15m
  chart:
    spec:
      chart: qbittorrent
      version: 22.4.5
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 5m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${QBITTORRENT_IP}
        ports:
          main:
            port: 10095 # Default qbittorrent port
    persistence:
      media:
        enabled: true
        type: nfs
        path: /mnt/playground/media
        mountPath: "/Media"
        server: 192.168.1.98
      config:
        enabled: true
        mountPath: "/config"
        targetSelectAll: true


    addons:
      vpn:
        type: gluetun
        killSwitch: true
        excludedNetworks_IPv4:
          - "192.168.1.0/24"
        excludedNetworks_IPv6: []
        env:
          VPN_SERVICE_PROVIDER: "purevpn"
          VPN_TYPE: "openvpn"
          OPENVPN_USER: ${VPN_USERNAME}
          OPENVPN_PASSWORD: ${VPN_PASSWORD}
    workload:
        main:
          podSpec:
            initContainers:
              initconfig:
                type: init
                enabled: true
                command: [ "sh", "/config/mam.sh" ]