apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: qbittorrent
      version: 22.4.5
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${QBITTORRENT_IP}
        ports:
          main:
            port: 10095 # Default qbittorrent port
    persistence:
      media:
        enabled: true
        type: nfs
        path: /mnt/playground/media
        mountPath: "/Media"
        server: 192.168.1.98
      configmap-vol:
        enabled: true
        type: configmap
        objectName: qbittorrent-custom-config
        expandObjectName: false
        optional: false
        defaultMode: "0777"
        items:
          - key:  qBittorrent.conf
            path: qBittorrent.conf
        targetSelector:
          qBittorrent:
            qBittorrent:
              mountPath: /config/qBittorrent.conf


    addons:
      vpn:
        type: gluetun
        killSwitch: true
        excludedNetworks_IPv4:
          - "192.168.1.0/24"
        excludedNetworks_IPv6: []
        env:
          VPN_SERVICE_PROVIDER: "purevpn"
          VPN_TYPE: "openvpn"
          OPENVPN_USER: ${VPN_USERNAME}
          OPENVPN_PASSWORD: ${VPN_PASSWORD}